### ISSUE TITLE
SEO & meta tags optimalizations

### ISSUE THREAD

**Issue by burningtree** [web3privacy/web#2]
The code needs to be optimised so that the website displays well, for example, in social media previews.

This is how previews looks currently:

<img width="750" alt="Screenshot 2024-02-02 at 13 47 21" src="https://github.com/web3privacy/web/assets/67269/b0865008-451c-4b22-a909-ffa2c54824b9">

**Comment by agonist** [comment]
Small question for this issue,

Do you mostly want to have nice looking links preview and have the meta tags filled properly, or do you also want to have things setup properly for SEO? Meaning for example the description should have the appropriate length to make search engines happy.

**Comment by burningtree** [comment]
I believe the main concern is social media previews. SEO rules is not that important.
